### ISSUE TITLE
大佬您好我想问下为什么用pip指令和nb指令安装都报错

### ISSUE THREAD

**Issue by Nana7mij** [axStar/nonebot_plugin_warframe_clock#1]
![图片](https://user-images.githubusercontent.com/91075288/176344186-922138ee-d57c-40a2-8930-c9ceb92491b3.png)

**Comment by axStar** [comment]
镜像源问题，没有找到插件。

---
**使用下面这个命令安装：**
`nb plugin install nonebot-plugin-warframe-clock -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by Nana7mij** [comment]
okok，谢谢大佬♪(･ω･)ﾉ
